### ISSUE TITLE
Most folders are without code

### ISSUE THREAD

**Issue by akuckartz** [microsoft/MediaWiki-Extensions#1]
When will the code be made available?

**Comment by jeffw16** [comment]
Hi @akuckartz,

This repo is being maintained by volunteers who are FTEs at Microsoft. We work on this in our spare time. We are still working on processing the code and will release them when they have had all first-party proprietary code scrubbed and when the extension code is tested.

Please note that the team who wrote this code is no longer working on it, so they are not participating in this open sourcing initiative.

Thanks for your patience!
